add ssh instance connection

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -15,7 +15,7 @@
 # specific language governing permissions and limitations
 # under the License.
 
-version: '3'
+version: "3"
 
 dotenv: [.env]
 
@@ -30,26 +30,25 @@ vars:
     sh: git describe --tags --abbrev=0 2>/dev/null || echo latest
   J: "{}"
   RUNTIMES: "golang,nodejs,php,python"
-  COMMIT_ID: 
+  COMMIT_ID:
     sh: git rev-parse --short HEAD
 
 tasks:
-
   default:
-  - task --list-all
+    - task --list-all
 
   setup:
-  # check we are running in ubuntu 
-  - grep '^ID=' /etc/os-release | grep -i ubuntu
-  - if ! which python3 | grep python3 ; then echo "python3 not found" ; exit 1; fi
-  - sudo apt-get -y install python3-pip python3-virtualenv
-  - python3 -m pip install ipython watchdog requests cram
-  
+    # check we are running in ubuntu
+    - grep '^ID=' /etc/os-release | grep -i ubuntu
+    - if ! which python3 | grep python3 ; then echo "python3 not found" ; exit 1; fi
+    - sudo apt-get -y install python3-pip python3-virtualenv
+    - python3 -m pip install ipython watchdog requests cram
+
   image-tag:
     silent: true
     cmds:
-      - git tag -d $(git tag) 
-      - | 
+      - git tag -d $(git tag)
+      - |
         if test -n "{{.RT}}"
         then git tag -f {{.BASETAG}}-{{.RT}}.$(date +%y%m%d%H%M)
         else git tag -f {{.BASETAG}}.$(date +%y%m%d%H%M)
@@ -58,50 +57,50 @@ tasks:
 
   compile: go build -o proxy
 
-  test: 
+  test:
     dir: openwhisk
     cmds:
-    - go test -v
+      - go test -v
 
-  docker-login: 
+  docker-login:
     ignore_error: true
     cmds:
-    - echo ${MY_DOCKER_HUB_TOKEN:-$DOCKER_HUB_TOKEN} | docker login -u ${MY_DOCKER_HUB_USER:-$DOCKER_HUB_USER} --password-stdin registry.hub.docker.com
-    - >
-      {{.DRY}} docker run -it --rm --privileged tonistiigi/binfmt --install all
-    - >
-      {{.DRY}} docker buildx create --name mybuilder --bootstrap --use
+      - echo ${MY_DOCKER_HUB_TOKEN:-$DOCKER_HUB_TOKEN} | docker login -u ${MY_DOCKER_HUB_USER:-$DOCKER_HUB_USER} --password-stdin registry.hub.docker.com
+      - >
+        {{.DRY}} docker run -it --rm --privileged tonistiigi/binfmt --install all
+      - >
+        {{.DRY}} docker buildx create --name mybuilder --bootstrap --use
 
   clean-images:
-    - docker images -a | grep ghcr.io/nuvolaris | awk '{print $3}' | xargs docker rmi -f 
+    - docker images -a | grep ghcr.io/nuvolaris | awk '{print $3}' | xargs docker rmi -f
     - yes | docker buildx prune
 
   build-common:
     dir: "runtime/common/{{.COMMON_VER}}"
     cmds:
-    - |
-      if test -n "{{.PUSH}}"
-      then {{.DRY}} docker buildx build -t "{{.COMMON}}" --platform linux/amd64,linux/arm64 . --push
-      else {{.DRY}} docker buildx build -t "{{.COMMON}}" . --load
-      fi
+      - |
+        if test -n "{{.PUSH}}"
+        then {{.DRY}} docker buildx build -t "{{.COMMON}}" --platform linux/amd64,linux/arm64 . --push
+        else {{.DRY}} docker buildx build -t "{{.COMMON}}" . --load
+        fi
 
   build-runtime:
-    requires: { vars: [RT, VER] } 
+    requires: { vars: [RT, VER] }
     dir: "runtime/{{.RT}}/{{.VER}}"
     cmds:
-    - |
-      BASEIMG=$(echo "${MY_DOCKER_HUB_REGISTRY:-$DOCKER_HUB_REGISTRY}")
-      RUNTIME="{{.BASEIMG}}/openserverless-runtime-{{.RT}}-{{.VER}}:{{.TAG}}"
-      if test -n "{{.PUSH}}"
-      then 
-        {{.DRY}} docker buildx build -t "$RUNTIME" --build-arg COMMON="{{.COMMON}}" --platform linux/amd64,linux/arm64 . --push    
-      else {{.DRY}} docker buildx build -t "$RUNTIME" --build-arg COMMON="{{.COMMON}}" . --load
-      fi
-      echo "Built $RUNTIME"
+      - |
+        BASEIMG=$(echo "${MY_DOCKER_HUB_REGISTRY:-$DOCKER_HUB_REGISTRY}")
+        RUNTIME="{{.BASEIMG}}/openserverless-runtime-{{.RT}}-{{.VER}}:{{.TAG}}"
+        if test -n "{{.PUSH}}"
+        then 
+          {{.DRY}} docker buildx build -t "$RUNTIME" --build-arg COMMON="{{.COMMON}}" --platform linux/amd64,linux/arm64 . --push    
+        else {{.DRY}} docker buildx build -t "$RUNTIME" --build-arg COMMON="giusdp/mycommon:0.1.0-testing.2408220918" . --load
+        fi
+        echo "Built $RUNTIME"
 
   build-lang:
     desc: build images for one runtime
-    requires: {vars: [RT] }
+    requires: { vars: [RT] }
     vars:
       DIRS:
         sh: ls -d  runtime/{{.RT}}/v* || echo ""
@@ -113,14 +112,14 @@ tasks:
 
   build:
     silent: true
-    requires: { vars: [TAG,RUNTIMES] } 
+    requires: { vars: [TAG, RUNTIMES] }
     vars:
       RT_REGEX:
         sh: echo "{{.RUNTIMES}}" | tr ',' '|'
       SPECIFIC_RT:
         sh: echo "{{.TAG}}" | grep -E -o '({{.RT_REGEX}})' || echo ''
     cmds:
-      - |        
+      - |
         if [ -z "{{.SPECIFIC_RT}}" ];
         then
           echo "==> BUILDING RUNTIMES {{.RUNTIMES}}"
@@ -133,34 +132,41 @@ tasks:
         fi
 
   build-and-push:
-  - task build PUSH=y DRY={{.DRY}}
+    - task build PUSH=y DRY={{.DRY}}
 
   run:
     desc: run a runtime
-    requires: { vars: [RT, VER] } 
+    requires: { vars: [RT, VER] }
     dir: "runtime/{{.RT}}/{{.VER}}"
     cmds:
-    - >
-      {{.DRY}} docker run -p 8080:8080 -ti "{{.BASEIMG}}/runtime-{{.RT}}-{{.VER}}:{{.TAG}}"
+      - >
+        {{.DRY}} docker run -p 8080:8080 -ti "{{.BASEIMG}}/openserverless-runtime-{{.RT}}-{{.VER}}:{{.TAG}}"
 
   debug:
     desc: debug a runtime
-    requires: { vars: [RT, VER] } 
+    requires: { vars: [RT, VER] }
     dir: "runtime/{{.RT}}/{{.VER}}"
     cmds:
-    - >
-      {{.DRY}} docker run -p 8080:8080 -ti 
-      --entrypoint=/bin/bash -v $PWD:/mnt 
-      -e OW_COMPILER=/mnt/bin/compile 
-      "{{.BASEIMG}}/runtime-{{.RT}}-{{.VER}}:{{.TAG}}"
-      
+      - >
+        {{.DRY}} docker run -p 8080:8080 -ti 
+        --entrypoint=/bin/bash -v $PWD:/mnt 
+        -e OW_COMPILER=/mnt/bin/compile 
+        "{{.BASEIMG}}/openserverless-runtime-{{.RT}}-{{.VER}}:{{.TAG}}"
+
   init:
     desc: intialize a runtime with a test
-    requires: { vars: [RT, VER, T] } 
+    requires: { vars: [RT, VER, T] }
     cmds:
-    - python3 packages/invoke.py init packages/{{.RT}}/{{.T}}.zip
+      - python3 packages/invoke.py init packages/{{.RT}}/{{.T}}.zip
 
   invoke:
     desc: invoke a runtime listening in port 8080, optionally with J=<json>
     cmds:
-    - python3 packages/invoke.py run '{{.J}}'
+      - python3 packages/invoke.py run '{{.J}}'
+
+  run-debug:
+    cmds:
+      - docker buildx build --platform linux/amd64 -t giusdp/mycomm . --load
+      - docker push giusdp/mycomm
+      - docker build -t "{{.BASEIMG}}/openserverless-runtime-python-v3.11vastai:{{.TAG}}" --build-arg COMMON="giusdp/mycomm:latest" -f runtime/python/v3.11vastai/Dockerfile runtime/python/v3.11vastai/
+      - task run RT=python VER=v3.11vastai
